### ISSUE TITLE
Expose server object

### ISSUE THREAD

**Issue by eshaham** [pascalw/dashbling#20]
Would be great to add a way to make calls to the hapi server object during initialization.
Some use cases:
- adding another server route
- adding an SSL certificate / integrate [Let's encrypt](https://www.npmjs.com/package/greenlock-hapi)
- server-side authentication

**Comment by pascalw** [comment]
Hey @eshaham that's a good suggestion indeed :-) I've opened a PR here https://github.com/pascalw/dashbling/pull/21, can you have a look if this would suffice for your use cases?

**Comment by eshaham** [comment]
@pascalw thanks so much, looks great!

**Comment by pascalw** [comment]
Closed via #21.
